CRITICAL - 2022-02-28 02:13:51 --> Undefined property: App\Controllers\Home::$load
#0 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 22)
#1 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-28 02:14:23 --> Undefined property: App\Controllers\Home::$load
#0 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 22)
#1 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-28 02:14:23 --> Undefined property: App\Controllers\Home::$load
#0 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 22)
#1 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-28 02:19:23 --> Class "App\Controllers\FormModel" not found
#0 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#1 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-28 02:19:37 --> Invalid file: contact_form.php
#0 C:\xampp\htdocs\codeigniter4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('contact_form.ph...')
#1 C:\xampp\htdocs\codeigniter4\system\Common.php(1089): CodeIgniter\View\View->render('contact_form', Array, true)
#2 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(32): view('contact_form', Array)
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-28 02:36:59 --> CodeIgniter\HTTP\RedirectResponse::to(): Argument #2 ($code) must be of type ?int, array given, called in C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php on line 39
#0 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(39): CodeIgniter\HTTP\RedirectResponse->to('/Home', Array)
#1 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->save()
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-28 02:40:06 --> Undefined variable $task_title
#0 C:\xampp\htdocs\codeigniter4\app\Views\add.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 19)
#1 C:\xampp\htdocs\codeigniter4\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniter4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\codeigniter4\system\Common.php(1089): CodeIgniter\View\View->render('add', Array, true)
#4 C:\xampp\htdocs\codeigniter4\app\Controllers\Home.php(18): view('add')
#5 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(825): App\Controllers\Home->add()
#6 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-28 05:01:27 --> scandir(C:\xampp\htdocs\codeigniter4\Modules/): The system cannot find the file specifi (code: 2)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'scandir(C:\\xamp...', 'C:\\xampp\\htdocs...', 57)
#1 C:\xampp\htdocs\codeigniter4\app\Config\Routes.php(57): scandir('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(706): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-02-28 05:01:27 --> scandir(C:\xampp\htdocs\codeigniter4\Modules/): The system cannot find the file specifi (code: 2)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'scandir(C:\\xamp...', 'C:\\xampp\\htdocs...', 57)
#1 C:\xampp\htdocs\codeigniter4\app\Config\Routes.php(57): scandir('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(706): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#4 C:\xampp\htdocs\codeigniter4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\codeigniter4\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
